name: Deploy to Azure Function App

on:
  push:
    branches: [main]
  workflow_dispatch: {}

env:
  AZURE_FUNCTIONAPP_NAME: w2w-stremio
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "."
  NODE_VERSION: "22.x"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - run: npm ci --omit=dev
      - uses: Azure/functions-action@v2
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_5F2BFEC3B67646B887D38EA2143C7083 }}
          sku: flexconsumption
          remote-build: true
